### ISSUE TITLE
preliminary container for Reflector

### ISSUE THREAD

**Issue by Leopere** [lbryio/lbry-docker#4]
Reflector.go is an internally utilized appliance at lbryio, however there's no reason why it can't be publicly usable so I'm aiming to make it accessible via Docker.  The following is a list of objects in the way.

- [ ] Dockerfile

- [ ] Healthcheck

- [ ] Start.sh

- [ ] docker-compose.yml

- [ ] docker-entrypoint.sh [If needed]

- [ ] hub.docker.com/r/lbryio/

**Comment by Leopere** [comment]
Due to the status of https://github.com/lbryio/reflector.go building a release binary container might not make sense.  It may be smarter to release a compiler container which can produce a binary and/or run from source until the developer is closer to ready to have people running directly off release binaries *aka documented to some degree.

**Comment by Leopere** [comment]
Depends on https://github.com/lbryio/reflector.go/issues/21

**Comment by Leopere** [comment]
Progress report: 
Needs a staging environment that includes an S3 bucket and I'm still waiting to get a conversation arranged with @nikooo777 for official S3 buckets for this purpose.
